function [ fnames, coords ] = vk4_readStitchTileCfg ( fpath )
%VK4_READSTITCHTILECFG read a Tile Configuration file generated by the
%Grid Stitching plugin in Fiji
%
% NOTE: this is in the keyence library because I really only use it for
% restitching Keyence-made stitches
%
% PARAMETERS:
%   fpath : path to TileConfiguration.txt file
    
    lineNo = 1;
    fid = fopen (fpath);
    if fid < 0
        error ('keyence_readStitchTileCfg :: file not found (%s)', fpath);
    end
    % clear the first 4 lines -- they're useless
    for ii = 1:4
        fgetl (fid);
    end
    curr_line = fgetl (fid);
    ii = 1;
    while ischar (curr_line)            % read the rest of the lines
        line_split = strsplit (curr_line, '; ; ');
        % file name is first part of split
        [~, fname, ext] = fileparts (line_split{1});
        nums = cellfun (@str2double, ...
                        strsplit (line_split{2}(2:end-1), ', '));
        fnames{ii} = fname;
        coords(ii,:) = nums;
        % read next line
        curr_line = fgetl (fid);
        ii = ii + 1;
    end
    fclose (fid);
end
